# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  #vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

  steps:
    - task: UseDotNet@2 
      displayName: "Restore"
      inputs:
        version: '3.1.x'
        packageType: sdk
    - script: dotnet restore GatewaysManagement.API.csproj
      displayName: 'dotnet Restore'

    - task: UseDotNet@2
      displayName: "Build"
      inputs:
        version: '3.1.x'
        packageType: sdk
    - script: dotnet build --configuration $(buildConfiguration) GatewaysManagement.API.csproj
      displayName: 'dotnet build $(buildConfiguration) GatewaysManagement.API.csproj'

    - task: DotNetCoreCLI@2
      displayName: "Publish Artifacts"
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '-r linux-x64 --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: "ArtefactName"
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'ArtefactName'