version: '3.4'

services: 

  frontend:
    image: gatewayfrontend
    build:
      context: frontend
      dockerfile: Dockerfile
    environment: 
      - backendUrl=http://gatewaybackend
    ports:
      - "5902:80"
    depends_on: 
      - backend
  backend:
    image: gatewaybackend
    build: 
      context: GatewaysManagement.API
      dockerfile: Dockerfile
    ports: 
      - "5000:80"